using Microsoft.EntityFrameworkCore;

namespace aspbackend.model{
    /// <summary>
    /// generated by a scaffold command 
    /// dotnet ef dbcontext scaffold DefaultConnection Microsoft.EntityFrameworkCore.Sqlite
    /// </summary>
    public class UserContext : DbContext{
        public UserContext(DbContextOptions<UserContext> options) : base(options){}
        public DbSet<User> Users {get; set;}
        public DbSet<StoredPassword> StoredPasswords {get; set;}
    }
}